# coding: utf-8

"""
    Registry of Open Community Challenge API

    The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA   # noqa: E501

    The version of the OpenAPI document: 0.1.4
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import roccclient
from roccclient.models.person_create_response import PersonCreateResponse  # noqa: E501
from roccclient.rest import ApiException

class TestPersonCreateResponse(unittest.TestCase):
    """PersonCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PersonCreateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = roccclient.models.person_create_response.PersonCreateResponse()  # noqa: E501
        if include_optional :
            return PersonCreateResponse(
                person_id = '507f1f77bcf86cd799439011'
            )
        else :
            return PersonCreateResponse(
        )

    def testPersonCreateResponse(self):
        """Test PersonCreateResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
