---
title: "Using ROCC Client Library for Python in R"
author: "Thomas Schaffter, thomas.schaffter@sagebionetworks.org"
date: "Run on `r format(Sys.time(), '%c')`"
output:
  html_notebook:
    code_folding: show
---

```{r}
# Start from a clean environment
rm(list=ls())
```


```{r results='hide'}
# Use the package versions listed in renv.lock
renv::restore()

# Install dependencies
packages <- c(
  'dplyr',
  # 'fs',
  'ggplot2',
  # 'jsonlite',
  # 'parallel',
  # 'purrr',
  # 'renv',
  'reshape2',
  'reticulate',
  # 'rlist',
  # 'rprojroot',
  # 'stringr',
  # 'tibble',
  'tidyr'
  # 'xml2'
)

# TODO: Shall we also check the version of the package installed instead of just
# the name?
new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if (length(new.packages)) install.packages(new.packages)

# Import dependencies
noop <- lapply(packages, require, character.only = TRUE)
```

```{r}
# Activate Sage conda environment
use_condaenv("rocc", required = TRUE)
```

### List Tags

```{python}
from __future__ import print_function

import roccclient
from roccclient.rest import ApiException

# Defining the host is optional and defaults to http://example.com/api/v1
# See configuration.py for a list of all supported configuration parameters.
configuration = roccclient.Configuration(
    # host="http://host.docker.internal:8080/api/v1"  # local ROCC API service
    host="http://10.41.27.32:8080/api/v1"  # ROCC API service
)

with roccclient.ApiClient(configuration) as api_client:
    tag_api = roccclient.TagApi(api_client)

    tags = tag_api.list_tags(limit=100)
    print(f'number of tags: {len(tags.tags)}')
    print(f'tags: {tags}')
```

### List Challenges

```{python}
from __future__ import print_function

import roccclient
from roccclient.rest import ApiException

# Defining the host is optional and defaults to http://example.com/api/v1
# See configuration.py for a list of all supported configuration parameters.
configuration = roccclient.Configuration(
    # host="http://host.docker.internal:8080/api/v1"  # local ROCC API service
    host="http://10.41.27.32:8080/api/v1"  # ROCC API service
)

with roccclient.ApiClient(configuration) as api_client:
    challenge_api = roccclient.ChallengeApi(api_client)

    challenges = challenge_api.list_challenges(limit=100).challenges
    print(f'number of challenges: {len(challenges)}')
    print(f'challenge example: {challenges[1]}')
```
```{r rows.print=15, echo=FALSE}
challenges <- do.call(rbind, lapply(py$challenges, function(challenge) {
  data.frame(
    name=challenge['name'],
    status=challenge['status'],
    startDate=challenge['start_date'],
    endDate=challenge['end_date'],
    nOrganizers=length(challenge['organizers']),
    tags=paste(challenge['tags'], collapse=" | "),
    nSubmissions=challenge['challenge_results']['n_submissions'],
    nRegisteredParticipants=challenge['challenge_results']['n_registered_participants'],
    stringsAsFactors=FALSE
  )
}))

challenges
```

### Number of registered participants in Challenges

```{r fig.width=12}
challenges$nameWithYear = paste0(challenges$name, " (", substr(data$startDate, 1, 4), ")")

ggplot(challenges, aes(x=nRegisteredParticipants, y=reorder(nameWithYear, startDate))) +
  geom_bar(stat = 'identity', fill = "#619dff") +
  xlab("Number of registered participants") +
  ylab("Challenge")
```

### List upcoming Challenges

```{r}
challenges[challenges$status == 'upcoming',]
```

### List Organizers

```{python echo=FALSE}
from __future__ import print_function

import roccclient
from roccclient.rest import ApiException

# Defining the host is optional and defaults to http://example.com/api/v1
# See configuration.py for a list of all supported configuration parameters.
configuration = roccclient.Configuration(
    # host="http://host.docker.internal:8080/api/v1"  # local ROCC API service
    host="http://10.41.27.32:8080/api/v1"  # ROCC API service
)

with roccclient.ApiClient(configuration) as api_client:
    person_api = roccclient.PersonApi(api_client)

    # TODO: Use link returned to get the next page
    persons = person_api.list_persons(offset=0, limit=100).persons \
      + person_api.list_persons(offset=100, limit=100).persons \
      + person_api.list_persons(offset=200, limit=100).persons
```

```{r rows.print=15, echo=FALSE}
persons <- do.call(rbind, lapply(py$persons, function(person) {
  person = unlist(person)
  
  nChallengesOrganized = do.call(sum, lapply(py$challenges, function(challenge) {
    person['person_id'] %in% challenge['organizers']
  }))
  
  data.frame(
    firstName=person['first_name'],
    lastName=person['last_name'],
    organizations=paste(person['organizations'], collapse = ' | '),
    personId=person['person_id'],
    nChallengesOrganized=nChallengesOrganized,
    stringsAsFactors=FALSE
  )
}))

persons %>%
  arrange(firstName)
```

### List of most prolific Organizers at Sage Bionetworks

```{r rows.print=15}
persons %>%
  filter(across(organizations, ~ grepl('sage', .))) %>%
  arrange(desc(nChallengesOrganized)) %>%
  select(-organizations, -personId)
```

